export const words = {
  ru: {
    loaderText: 'Загружаем меню. <br> Пожалуйста подождите.',
    appError: 'Простите приложение временно недоступно. Пожалуйста обратитесь к официантку.',
    discountButtonText: 'Предложение дня',
    visitorNnativeLanguage: "Родной язык посетителя - ",
    portion: "порция",
    cost: "стоимость",
    pieces: "штуки",

    totalCost: "Стоимость блюд в корзине: <br>",
    yourOrderTitle: "Ваш заказ",
    sendOrder: "Отправить заказ",
    updateOrder: "Добавить к заказу",

    yourCart: "Корзина:",
    announcement: "",
    announcementText: "Выберите желаемые блюда, затем пригласите официанта и покажите ему корзину.",
    googleFedback: "Оставьте отзыв",
    deletePortionMessage: "Удалить порцию?",

    textSendOrder: "Заказ успешно отправлен!",
    textErrorSendOrder: "Ошибка при отправке заказа. Пожалуйста, попробуйте ещё раз или пригласите официанта.",
    textAskTableNumber: "Пожалуйста, введите номер стола. Его можно увидеть на QR-коде, который находится на вашем столе.",
    totalCostOrder: "Стоимость заказа: ",
    yourOrderButton: "Ваш заказ<br>№",
    payOrderButton: "Оплатить",

    tableNumber: "🍽️ Стол № ",
    orderNumber: "#️⃣ Номер заказа",
    newOrderMessage: "‼️🔴 Новый заказ!\n",
    updateOrderMessage: "‼️🟢 Обновление заказа\n",
    oldDishes: "🟨 Прошлые блюда:",
    newDishes: "🟩 Новые блюда:",
    listDishes: "📃 Список блюд:",

    IQRMenuLink: "Заказать меню",
    selectPaymentMethod: "Выберете способ оплаты",
    cash: "Наличные",
    bankCard: "Карта",
    cancelButton: "Отмена",
    waiterWillCome: "Спасибо! Скоро к вам придет официант.",
    errorInviteWaiter: "Что-то пошло не так, пожалуйста пригласите официанта",
    enterCorrectly: "Пожалуйста введите корректно номер стола",
    errorPayCode: "Неверный код! Пожалуйста уточните у официанта.",
    finishText: "Спасибо! Ждем Вас вновь!",
    inputPayCodeText: "Сейчас к вам придет официант. После оплаты пожалуйста введите код оплаты. Официант вам его сообщит.",
    textMessage: "💵 Оплата заказа!\n\nРодной язык посетителя - ${userLang}\n🍽️ Стол № ${tableNumber}\n💶💳 Способ оплаты - ${paymentMethod}\n#️⃣ Номер закза -\n${orderId}\n\n📃 Вот чек:\n ${orderListText}\n💰 Итого: ${totalCostMessage} ${currencySymbol}\n\n Код - Успешная оплата: ${sectetPayCode}",


  },
  
  en: {
    loaderText: 'Loading menu.<br>Please wait.',
    appError: 'Sorry, the app is temporarily unavailable. Please contact the waitress.',
    discountButtonText: 'Offer of the day',
    visitorNnativeLanguage: "Visitor's native language - ",
    portion: "portion",
    cost: "cost",
    pieces: "pieces",

    totalCost: "Total cost of dishes in the cart: <br>",
    yourOrderTitle: "Your order",
    sendOrder: "Send order",
    updateOrder: "Add to order",

    yourCart: "Cart:",
    announcement: "",
    announcementText: "Select the desired dishes, then call the waiter and show them the cart.",
    googleFedback: "Leave feedback",
    deletePortionMessage: "Delete portion?",

    textSendOrder: "Order sent successfully!",
    textErrorSendOrder: "Error sending order. Please try again or call the waiter.",
    textAskTableNumber: "Please enter your table number. You can find it on the QR code located on your table.",
    totalCostOrder: "Order cost: ",
    yourOrderButton: "Your order<br>№",

    tableNumber: "🍽️Table № ",
    orderNumber: "#️⃣ Order number",
    newOrderMessage: "‼️🔴 New order!\n",
    updateOrderMessage: "‼️🟢 Order update\n",
    oldDishes: "🟨 Previous dishes:",
    newDishes: "🟩 New dishes:",
    listDishes: "📃 List of dishes:",
    payOrderButton: "Pay",

    IQRMenuLink: "Order menu",
    selectPaymentMethod: "Choose a payment method",
    cash: "Cash",
    bankCard: "Card",
    cancelButton: "Cancel",
    waiterWillCome: "Thank you! A waiter will come to you soon.",
    errorInviteWaiter: "Something went wrong, please call a waiter.",
    enterCorrectly: "Please enter the table number correctly.",
    errorPayCode: "Invalid code! Please check with the waiter.",
    finishText: "Thank you! We look forward to seeing you again!",
    inputPayCodeText: "The waiter will be with you shortly. After making the payment, please enter the payment code that they will provide.",
    textMessage: "💵 Order payment!\n\nVisitor's native language - ${userLang}\n🍽️ Table № ${tableNumber}\n💶💳 Payment method - ${paymentMethod}\n#️⃣ Order number -\n${orderId}\n\n📃 Here is the receipt:\n ${orderListText}\n💰 Total: ${totalCostMessage} ${currencySymbol}\n\n Payment Success Code: ${sectetPayCode}"
  },

  tr: {
    loaderText: 'Menü yükleniyor.<br>Lütfen bekleyin.',
    appError: 'Üzgünüz, uygulama geçici olarak kullanılamıyor. Lütfen garsonla iletişime geçin.',
    discountButtonText: 'Günün Teklifi',
    visitorNnativeLanguage: "Ziyaretçinin ana dili - ",
    portion: "porsiyon",
    cost: "fiyat",
    pieces: "adet",

    totalCost: "Sepetteki yemeklerin toplam maliyeti: <br>",
    yourOrderTitle: "Siparişiniz",
    sendOrder: "Siparişi Gönder",
    updateOrder: "Siparişe Ekle",

    yourCart: "Sepet:",
    announcement: "",
    announcementText: "İstediğiniz yemekleri seçin, ardından garsonu çağırıp sepeti gösterin.",
    googleFedback: "Geri Bildirim Bırakın",
    deletePortionMessage: "Porsiyonu silmek istiyor musunuz?",

    textSendOrder: "Sipariş başarıyla gönderildi!",
    textErrorSendOrder: "Sipariş gönderilirken hata oluştu. Lütfen tekrar deneyin veya garsonu çağırın.",
    textAskTableNumber: "Lütfen masa numaranızı girin. Masa numaranızı masanızdaki QR kodunda bulabilirsiniz.",
    totalCostOrder: "Sipariş tutarı: ",
    yourOrderButton: "Siparişiniz<br>№",

    tableNumber: "🍽️ Masa № ",
    orderNumber: "#️⃣ Sipariş Numarası",
    newOrderMessage: "‼️🔴 Yeni Sipariş!\n",
    updateOrderMessage: "‼️🟢 Sipariş Güncellemesi\n",
    oldDishes: "🟨 Önceki yemekler:",
    newDishes: "🟩 Yeni yemekler:",
    listDishes: "📃 Yemek listesi:",
    payOrderButton: "Öde",

    IQRMenuLink: "Menüyü Sipariş Et",
    selectPaymentMethod: "Ödeme yöntemi seçin",
    cash: "Nakit",
    bankCard: "Kart",
    cancelButton: "İptal",
    waiterWillCome: "Teşekkürler! Garson yakında yanınıza gelecek.",
    errorInviteWaiter: "Bir hata oluştu, lütfen garsonu çağırın.",
    enterCorrectly: "Lütfen masa numarasını doğru girin.",
    errorPayCode: "Geçersiz kod! Lütfen garsona danışın.",
    finishText: "Teşekkür ederiz! Sizi tekrar görmek için sabırsızlanıyoruz!",
    inputPayCodeText: "Garson kısa süre içinde yanınıza gelecektir. Ödemeyi yaptıktan sonra, size verilen ödeme kodunu giriniz.",
    textMessage: "💵 Sipariş Ödemesi!\n\nZiyaretçinin ana dili - ${userLang}\n🍽️ Masa № ${tableNumber}\n💶💳 Ödeme yöntemi - ${paymentMethod}\n#️⃣ Sipariş numarası -\n${orderId}\n\n📃 İşte fişiniz:\n ${orderListText}\n💰 Toplam: ${totalCostMessage} ${currencySymbol}\n\n Ödeme Başarı Kodu: ${sectetPayCode}",
  },

  de: {
    loaderText: 'Menü wird geladen.<br>Bitte warten.',
    appError: 'Entschuldigung, die App ist vorübergehend nicht verfügbar. Bitte wenden Sie sich an die Bedienung.',
    discountButtonText: 'Angebot des Tages',
    visitorNnativeLanguage: "Muttersprache des Besuchers - ",
    portion: "Portion",
    cost: "Kosten",
    pieces: "Stück",

    totalCost: "Gesamtkosten der Gerichte im Warenkorb: <br>",
    yourOrderTitle: "Ihre Bestellung",
    sendOrder: "Bestellung senden",
    updateOrder: "Zur Bestellung hinzufügen",

    yourCart: "Warenkorb:",
    announcement: "",
    announcementText: "Wählen Sie die gewünschten Gerichte aus, rufen Sie dann die Bedienung und zeigen Sie den Warenkorb.",
    googleFedback: "Feedback hinterlassen",
    deletePortionMessage: "Portion löschen?",

    textSendOrder: "Bestellung erfolgreich gesendet!",
    textErrorSendOrder: "Fehler beim Senden der Bestellung. Bitte versuchen Sie es erneut oder rufen Sie die Bedienung.",
    textAskTableNumber: "Bitte geben Sie Ihre Tischnummer ein. Sie finden sie auf dem QR-Code an Ihrem Tisch.",
    totalCostOrder: "Bestellkosten: ",
    yourOrderButton: "Ihre Bestellung<br>Nr.",

    tableNumber: "🍽️ Tisch Nr. ",
    orderNumber: "#️⃣ Bestellnummer",
    newOrderMessage: "‼️🔴 Neue Bestellung!\n",
    updateOrderMessage: "‼️🟢 Bestellaktualisierung\n",
    oldDishes: "🟨 Vorherige Gerichte:",
    newDishes: "🟩 Neue Gerichte:",
    listDishes: "📃 Speisekarte:",
    payOrderButton: "Bezahlen",

    IQRMenuLink: "Menü bestellen",
    selectPaymentMethod: "Zahlungsmethode wählen",
    cash: "Barzahlung",
    bankCard: "Karte",
    cancelButton: "Abbrechen",
    waiterWillCome: "Danke! Die Bedienung kommt gleich zu Ihnen.",
    errorInviteWaiter: "Etwas ist schiefgelaufen, bitte rufen Sie die Bedienung.",
    enterCorrectly: "Bitte geben Sie die Tischnummer korrekt ein.",
    errorPayCode: "Ungültiger Code! Bitte fragen Sie die Bedienung.",
    finishText: "Vielen Dank! Wir freuen uns auf Ihren nächsten Besuch!",
    inputPayCodeText: "Die Bedienung wird in Kürze bei Ihnen sein. Nach der Zahlung geben Sie bitte den Zahlungs-Code ein, den Sie erhalten haben.",
    textMessage: "💵 Bestellzahlung!\n\nMuttersprache des Besuchers - ${userLang}\n🍽️ Tisch Nr. ${tableNumber}\n💶💳 Zahlungsmethode - ${paymentMethod}\n#️⃣ Bestellnummer -\n${orderId}\n\n📃 Hier ist Ihre Quittung:\n ${orderListText}\n💰 Gesamt: ${totalCostMessage} ${currencySymbol}\n\n Zahlungserfolgs-Code: ${sectetPayCode}",
  },

}